# Домашнее задание к семинару S01

Тема: настройка рабочей среды, работа с Git, структура репозитория и базовые операции в NumPy.

---

## 1. Цель

Закрепить:

- умение работать с публичным репозиторием на GitHub на базе шаблона `aie-student-template`;
- базовый цикл работы с Git (clone, add, commit, push);
- структуру каталога `homeworks/` в студенческом репозитории;
- минимальные навыки работы с NumPy (создание массивов, индексирование, простые операции).

---

## 2. Задание

### 2.1. Репозиторий на GitHub

1. Создать **публичный** репозиторий на GitHub на основе шаблона `aie-student-template`:
   - зайти на страницу шаблона;
   - нажать кнопку «Use this template»;
   - выбрать создание нового репозитория в своём аккаунте;
   - задать осмысленное имя репозитория (по инструкции курса).
2. Убедиться, что репозиторий создан и доступен по публичной ссылке.

### 2.2. Локальная настройка Git

1. Клонировать созданный репозиторий к себе на компьютер.
2. Настроить Git, если ранее не настраивался (имя и e-mail пользователя).
3. Убедиться, что команды `git status` и `git log` работают и показывают состояние репозитория.

### 2.3. Структура для семинара S01

1. В корне репозитория создать папку `homeworks/`, если её ещё нет.
2. Внутри `homeworks/` создать папку `HW01/`.
3. В папке `homeworks/HW01/` создать файл `HW01.ipynb` с кодом по NumPy.

### 2.4. Содержание файла с NumPy

В файле `HW01.ipynb` должны быть:

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

Желательно добавить несколько комментариев в коде, кратко поясняющих, что делает каждая операция.

---

## 3. Требования к структуре и именованию

Обязательная структура к дедлайну:

- в корне репозитория: папка `homeworks/`;
- внутри неё: папка `HW01/`;
- внутри папки `HW01/`: основной ноутубук `HW01.ipynb`.

Требования:

- названия папок и файлов должны быть **строго такими**, как указано выше (регистр букв имеет значение);
- репозиторий должен быть **публичным**;
- работа должна быть закоммичена и отправлена (`git push`) в удалённый репозиторий.

---

## 4. Критерии зачёта

Домашнее задание считается зачтённым, если:

1. Репозиторий создан на основе `aie-student-template` и является публичным.
2. В репозитории присутствует папка `homeworks/HW01/` с файлом `HW01.ipynb`.
3. Файл открывается и содержит:
   - импорт NumPy;
   - не менее трёх осмысленных примеров операций с массивами (создание, индексирование, простые вычисления).
4. Код выполняется без ошибок при стандартном запуске (при наличии установленного NumPy).

Дополнительно поощряется (но не обязательно для зачёта):

- наличие кратких текстовых комментариев в коде;
- использование нескольких разных способов создания массивов;
- примеры с двумерными массивами.

---

## 5. Сроки и порядок сдачи

- Работа выполняется **индивидуально**.
- Дедлайн и ссылка на шаблон `aie-student-template` будут указаны в объявлении по курсу.
- Фактом сдачи работы считается наличие к указанному дедлайну:
  - публичного репозитория;
  - структуры `homeworks/HW01/`;
  - файла с NumPy-примером в репозитории.


In [8]:
import numpy as np

In [9]:
# 1. Примеры создания массивов

# Из обычного списка
list_array = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", list_array)

# С использованием функции zeros
zeros_array = np.zeros((3, 3))
print("Массив из нулей (3x3):\n", zeros_array)

# С использованием функции ones
ones_array = np.ones(4)
print("Массив из единиц:", ones_array)

# С использованием функции arange
arange_array = np.arange(0, 10, 2)
print("Массив с использованием arange:", arange_array)

Массив из списка: [1 2 3 4 5]
Массив из нулей (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Массив из единиц: [1. 1. 1. 1.]
Массив с использованием arange: [0 2 4 6 8]


In [10]:
# 2. Демонстрация атрибутов

# Вывод формы (shape) и типа данных (dtype) для одного из массивов
print("\nАтрибуты zeros_array:")
print("Форма (shape):", zeros_array.shape)
print("Тип данных (dtype):", zeros_array.dtype)


Атрибуты zeros_array:
Форма (shape): (3, 3)
Тип данных (dtype): float64


In [11]:
# 3. Примеры индексирования и срезов

# Создадим тестовый массив для индексирования
test_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Исходный массив для индексирования: \n", test_array)

# Получение отдельного элемента (например, элемент в первой строке, втором столбце)
single_element = test_array[0, 1]
print("Отдельный элемент (0, 1):", single_element)

# Извлечение подмассива с помощью среза (например, первые две строки, все столбцы)
subarray = test_array[:2, :]
print("Подмассив (первые 2 строки):\n", subarray)

Исходный массив для индексирования: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Отдельный элемент (0, 1): 20
Подмассив (первые 2 строки):
 [[10 20 30]
 [40 50 60]]


In [12]:
# 4. Примеры векторных операций и базовых статистик

# Создадим два массива для операций
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nМассив a:", a)
print("Массив b:", b)

# Поэлементное сложение массивов
sum_array = a + b
print("Поэлементное сложение (a + b):", sum_array)

# Поэлементное умножение массивов
product_array = a * b
print("Поэлементное умножение (a * b):", product_array)

# Вычисление средней величины (mean) для одного из массивов
mean_value = np.mean(a)
print("Среднее значение массива a:", mean_value)

# Вычисление суммы элементов массива
sum_elements = np.sum(b)
print("Сумма элементов массива b:", sum_elements)


Массив a: [1 2 3]
Массив b: [4 5 6]
Поэлементное сложение (a + b): [5 7 9]
Поэлементное умножение (a * b): [ 4 10 18]
Среднее значение массива a: 2.0
Сумма элементов массива b: 15
